using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.0-default-dev-local")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTitleAttribute("Template")]
[assembly: AssemblyDescriptionAttribute("Template Description")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("Template")]

